[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/client/**", "node_modules/@prisma/client/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
